Adf 001 create navigation bar
rohan-004s/AgentDiscoveries-TS pull request #4
Opened 2022-10-26 13:46 UTC by MatthewCrossley

This PR adds in all the components required to have a navigation bar on web pages.

The style and design is subject to change

2022-10-26 14:54 UTC, BogRad97 commented
Something that I've missed in the previous PR, you'll need to add `export default {}` as placeholders for `HomePage.tsx`, `LoginPage.tsx` and `ProfilePage.tsx`, otherwise I'm getting errors when running the tests

2022-10-26 14:59 UTC, MatthewCrossley commented
We did see those errors, however, we felt that those errors aren't related to this pull request. I could open a seperate pull request for that but it might create merge conflicts for @maryam-awan-04's team since they are also working on those files

2022-10-26 15:02 UTC, BogRad97 commented
I'd still fix them because it's preferable to leave the main branch in a clean state. You're right that it would create merge conflicts, but those should be easy to fix, and in the early stages of the project when everyone's working in the same areas, they will be unavoidable later (and it will be good practice to deal with them and learn how to solve them)

2022-10-27 09:11 UTC, AndrewYHuang requested changes, later dismissed
Good start! Just a few recommendations :)

2022-10-27 09:11 UTC, AndrewYHuang commented on agent-discoveries-frontend/src/components/navbar/Navbar.tsx
> +const Navbar: React.FC = () => {
I generally prefer to let TypeScript infer the type from the react return type :)

Here's an awesome blog post about component types
https://fildon.me/blog/seeing-through-jsx-to-understand-react-component-types/

2022-10-27 09:11 UTC, AndrewYHuang commented on package.json
> +    "sass": "^1.55.0"
Ahh - so you're going to want have installed this as a dev dependency (`npm install -D sass`) rather than a straight-up dependency. `sass` compiles into css, and it's quite nice that Vite does that for us automatically.

Do you need to tell the others about sass? (it might be better to use just pure css - css has variables now so there is less functional reason to use `sass` anymore ngl)

2022-10-27 09:39 UTC, MatthewCrossley commented on agent-discoveries-frontend/src/components/navbar/Navbar.tsx
> +const Navbar: React.FC = () => {
Done

2022-10-27 09:39 UTC, MatthewCrossley commented on package.json
> +    "sass": "^1.55.0"
Removed the sass dependency

2022-10-27 09:59 UTC, AndrewYHuang commented
btw - I've added github actions for CI, if you merge main into this branch, you should get CI running :)

2022-10-27 10:03 UTC, AndrewYHuang commented
Oh balls, my bad

2022-10-27 10:17 UTC, AndrewYHuang commented
Have just fixed the frontend test script!

2022-10-27 10:55 UTC, MatthewCrossley commented
I swear to god this works on my machine

2022-10-27 10:56 UTC, AndrewYHuang commented
[Here's how to update snapshots](https://vitest.dev/guide/snapshot.html#updating-snapshots)

Sometimes the vscode plugins are fancy and have a button that does that for you :')

2022-10-27 13:24 UTC, merged